# Generated by Django 6.0.3 on 2026-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipping', 'Shipping'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
