# Generated by Django 6.0.3 on 2026-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPING', 'Đang giao'), ('DELIVERED', 'Đã giao'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
    ]
