# Generated by Django 6.0.3 on 2026-05-07 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_status'),
    ]

    operations = [

        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Chưa cập nhật'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(
                max_length=200,
                default='Khách hàng'
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(
                max_length=20,
                default='0000000000'
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),

        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('COD', 'Thanh toán khi nhận hàng'),
                    ('BANKING', 'Chuyển khoản')
                ],
                default='COD',
                max_length=20
            ),
        ),

    ]