# Generated by Django 6.0.3 on 2026-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shopreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
